---
title: "Aberdeen 2011 Census"

output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(sf)
library(flexdashboard)
library(mapview)
library(gt)
library(cowplot)
library(plotly)
library(viridis)

#theme_set(theme_cowplot())
```


```{r}
#load data and shapefiles 

simd_zones <- read_csv(here("data", "SIMD+2020v2+-+datazone+lookup.csv"))

simd_indicators <- read_csv(here("data", "SIMD2020v2_indicators.csv"))

datazone_sf <- st_read(here("data", "sc_dz_11.shp"), quiet = T)

general_health <- read_csv(here("data", "SNS Data Zone 2011 blk", "QS302SC.csv"))

#long_term_health_condition <- QS304SC

ethnicity <- read_csv(here("data", "SNS Data Zone 2011 blk", "KS201SC.csv"))

english_skills <- read_csv(here("data", "SNS Data Zone 2011 blk", "QS213SC.csv"))

#country_birth <- KS204SC

position_in_communal <- read_csv(here("data", "SNS Data Zone 2011 blk", "QS419SC.csv"))

#method_travel_work <- QS701SC

```

```{r}
#join SIMD files
#remove "%" and "*" and make numeric

ethnicity <-
  rename(ethnicity,
         all_people_ethnicity = "All people",
         Polish = "White: Polish")


english_skills <-
  rename(english_skills,
         data_zone = "X1",
         all_people_over_3 = "All people aged 3 and over",
         understands_only = "Understands but does not speak read or write English",
         speaks_only = "Speaks but does not read or write English",
         no_skills = "No skills in English"
         )

english_skills <-
  mutate(english_skills,
         cant_read = (no_skills + understands_only + speaks_only)/all_people_over_3) %>%
  mutate(cant_read = cant_read * 100)

position_in_communal <- 
  rename(position_in_communal,
         data_zone = "X1",
         total_communal = "All people in communal establishments",
         resident_communal = "Resident (1)",
         staff_communal = "Staff or owner",
         family_communal = "Family member or partner of staff or owner")

general_health <-
  rename(general_health,
         data_zone = "X1",
         all_people = "All people",
         very_good = "Very good health",
         good = "Good health",
         fair = "Fair health",
         bad = "Bad health",
         very_bad = "Very bad health")

general_health <-
  mutate(general_health,
         bad_health = (bad + very_bad)/all_people * 100,
         self_reported_health = (very_good * 5 + good * 4 + fair * 3 + bad * 2 + very_bad * 1)/all_people) 

simd <- full_join(simd_indicators, simd_zones, by = c("Data_Zone" = "DZ"))

simd <- left_join(simd, position_in_communal, by = c("Data_Zone" = "data_zone"))

simd <- left_join(simd, general_health, by = c("Data_Zone" = "data_zone"))

simd <- left_join(simd, english_skills, by = c("Data_Zone" = "data_zone"))

simd <- left_join(simd, ethnicity, by = c("Data_Zone" = "X1"))
# why do these joins change numberics to characters??

simd <- 
simd %>%
  mutate(across(everything(), ~ str_remove_all(., "%")),
         across(everything(), ~ str_remove_all(., "\\*")),
         across(Total_population:nocentralheat_rate, ~ as.numeric(.)),
         across(SIMD2020v2_Rank:Population, ~ as.numeric(.)),
         across(total_communal:family_communal, ~ as.numeric(.)),
         across(all_people:self_reported_health, ~as.numeric(.)),
         across(all_people:very_bad, ~ as.numeric(.)),
         across(all_people_over_3:cant_read, ~ as.numeric(.)),
         total_communal_perc = total_communal/Total_population *100,
         perc_white = as.numeric(White)/as.numeric(all_people_ethnicity) * 100,
         perc_not_white = 100 - perc_white,
         perc_Polish = as.numeric(Polish)/as.numeric(all_people_ethnicity) * 100)
```


```{r}
#select Aberdeen City areas' data 
#join to shapefile

aberdeen <-
  simd %>%
  filter(Council_area == "Aberdeen City")

aberdeen_data_zones <- pull(aberdeen, Data_Zone)

aberdeen_sf <- filter(datazone_sf, DataZone %in% aberdeen_data_zones)

aberdeen_sf <-
  merge(aberdeen_sf, aberdeen, by.x = "DataZone", by.y = "Data_Zone")

aberdeen_sf <-
aberdeen_sf %>% mutate(pop_per_km2 = TotPop2011/StdAreaKm2)

```


```{r}
# p <-
# ggplot(data = aberdeen, aes(y = overcrowded_rate, x = Intermediate_Zone, label = Data_Zone)) +
#   geom_boxplot() +
#   geom_point(size=4, aes(colour = factor(SIMD2020v2_Decile))) +
#     scale_color_viridis(discrete=TRUE) +
#   geom_point(size = 2) +
#   scale_fill_viridis() +
#   coord_flip() +
#   theme(legend.title = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), legend.position="bottom", plot.title = element_text(hjust = 0.5)) +
#   ggtitle("People living in overcrowed homes (%)") 
# 
# ggplotly(p, tooltip = c("label"))
# 
# 
# polish_plot <- ggplot(data = aberdeen, aes(x = SIMD2020v2_Decile, label = DZname)) +
#   geom_jitter(aes(y = perc_Polish, color = cant_read)) +
#   scale_color_viridis() +
#   scale_x_reverse(breaks = scales::pretty_breaks(10)) +
#   labs(x = "Deprivation Decile (lower = more deprived)", y = "Polish (% total population)") +
#   ggtitle("Polish Ethnicity and Deprivation") +
#   theme_cowplot()
# 
# ggplotly(polish_plot, tooltip = c("label"))
# 
# non_white_plot <- ggplot(data = aberdeen, aes(x = SIMD2020v2_Decile, label = DZname)) +
#   geom_jitter(aes(y = perc_not_white, color = cant_read)) +
#   scale_color_viridis() +
#   scale_x_reverse(breaks = scales::pretty_breaks(10)) +
#   labs(x = "Deprivation Decile (lower = more deprived)", y = "Non-white (% total population)") +
#   ggtitle("Non-white Ethnicity and Deprivation") +
#   theme_cowplot()
# 
# ggplotly(non_white_plot, tooltip = c("label"))
# 
# plot_grid(polish_plot, non_white_plot)
```


People in communal establishments
=====================================

Row
-------------------------------------

###

```{r}
aberdeen_sf %>%
  select(DataZone, Name, Total_population, SIMD2020v2_Decile, total_communal_perc) %>%
  mapview(
    map.types = "OpenStreetMap",
    zcol = "total_communal_perc", 
    label = aberdeen_sf$Name,
    layer.name = "in communal estab. (%)",
    alpha.regions = 0.8
    )
```


###

```{r}
#

aberdeen %>%
  select(Data_Zone, Intermediate_Zone, Total_population, total_communal_perc, SIMD2020v2_Decile) %>%
   filter(total_communal_perc >10) %>%
   arrange(desc(total_communal_perc)) %>%
  gt() %>%
  fmt_number(columns = vars(total_communal_perc), decimals = 0) %>%
  tab_header(
    title = "Areas with most living/working communally", 
    subtitle = "Data zones with >10% of population living or working in communal establishments") %>%
  cols_label(
    Data_Zone = "Data Zone",
    Intermediate_Zone = "Area", 
    Total_population = "Population", 
    total_communal_perc = "Communal (%)",
    SIMD2020v2_Decile = "SIMD Decile")  %>%
  tab_options(container.height = 400)
```


People reporting poor health
=====================================

Row
-------------------------------------

###

```{r}
aberdeen_sf %>%
  select(DataZone, Name, Total_population, SIMD2020v2_Decile, bad_health) %>%
  mapview(
    map.types = "OpenStreetMap",
    zcol = "bad_health", 
    label = aberdeen_sf$Name,
    layer.name = "poor health (%)",
    alpha.regions = 0.8
    )
```


###

```{r}
#

aberdeen %>%
  select(Data_Zone, Intermediate_Zone, Total_population, bad_health, SIMD2020v2_Decile) %>%
   filter(bad_health > 5) %>%
   arrange(desc(bad_health)) %>%
  gt() %>%
  fmt_number(columns = vars(bad_health), decimals = 0) %>%
  tab_header(
    title = "Poor health", 
    subtitle = "Data zones with > 5% reporting bad or very bad health") %>%
  cols_label(
    Data_Zone = "Data Zone",
    Intermediate_Zone = "Area", 
    Total_population = "Population", 
    bad_health = "Poor health (%)",
    SIMD2020v2_Decile = "SIMD Decile")  %>%
  tab_options(container.height = 400)
```


People who can't read English
=====================================

Row
-------------------------------------

###

```{r}
aberdeen_sf %>%
  select(DataZone, Name, Total_population, SIMD2020v2_Decile, cant_read) %>%
  mapview(
    map.types = "OpenStreetMap",
    zcol = "cant_read", 
    label = aberdeen_sf$Name,
    layer.name = "can't read English (%)",
    alpha.regions = 0.8
    )
```


###

```{r}
#

aberdeen %>%
  select(Data_Zone, Intermediate_Zone, Total_population, cant_read, SIMD2020v2_Decile) %>%
   filter(cant_read > 10) %>%
   arrange(desc(cant_read)) %>%
  gt() %>%
  fmt_number(columns = vars(cant_read), decimals = 0) %>%
  tab_header(
    title = "Cannot read English", 
    subtitle = "Data zones with > 10% cannot read English") %>%
  cols_label(
    Data_Zone = "Data Zone",
    Intermediate_Zone = "Area", 
    Total_population = "Population", 
    cant_read = "Can't read (%)",
    SIMD2020v2_Decile = "SIMD Decile")  %>%
  tab_options(container.height = 400)
```


People who are not ethnically white
=====================================

Row
-------------------------------------

###

```{r}
aberdeen_sf %>%
  select(DataZone, Name, Total_population, SIMD2020v2_Decile, perc_not_white) %>%
  mapview(
    map.types = "OpenStreetMap",
    zcol = "perc_not_white", 
    label = aberdeen_sf$Name,
    layer.name = "non-white ethnicity (%)",
    alpha.regions = 0.8
    )
```


###

```{r}
#

aberdeen %>%
  select(Data_Zone, Intermediate_Zone, Total_population, perc_not_white, SIMD2020v2_Decile) %>%
   filter(perc_not_white > 10) %>%
   arrange(desc(perc_not_white)) %>%
  gt() %>%
  fmt_number(columns = vars(perc_not_white), decimals = 0) %>%
  tab_header(
    title = "Largest non-white populations", 
    subtitle = "Data zones with > 10% not ethnically white") %>%
  cols_label(
    Data_Zone = "Data Zone",
    Intermediate_Zone = "Area", 
    Total_population = "Population", 
    perc_not_white = "non-white (%)",
    SIMD2020v2_Decile = "SIMD Decile")  %>%
  tab_options(container.height = 400) 
```


Sources
=====================================

Row
-------------------------------------
###

Data from 2011 Scotland Census
https://www.scotlandscensus.gov.uk/ods-web/data-warehouse.html

Map shapefiles from https://data.gov.uk/dataset/ab9f1f20-3b7f-4efa-9bd2-239acf63b540/data-zone-boundaries-2011

Code and data at https://github.com/JessButler/census


